version: '3.9'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build: ./docker/php
        container_name: php
        volumes:
            - ./:/var/www/html

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        command: /bin/bash -c "redis-server --appendonly yes && echo never > /sys/kernel/mm/transparent_hugepage/enabled"
        volumes:
            - ./docker/redis:/data
        environment:
            - REDIS_PASSWORD=${DB_PASSWORD}
            - REDIS_PORT=6379
            - REDIS_DATABASES=1
