version: '3.9'

services:
    nginx:
        image: nginx:1.26
        container_name: php-fpm-nginx
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build: ./docker/php
        container_name: php-fpm-php
        volumes:
            - ./:/var/www/html

    redis:
        image: redis:7.2
        container_name: php-fpm-redis
        restart: always
        command: /bin/bash -c "redis-server --appendonly yes && echo never > /sys/kernel/mm/transparent_hugepage/enabled"
        volumes:
            - ./docker/redis:/data
        environment:
            - REDIS_PORT=6379
            - REDIS_DATABASES=1

networks:
    default:
        name: php-fpm
